"""Clean initial migration

Revision ID: 26962f244e19
Revises: 
Create Date: 2025-05-25 12:15:14.492741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26962f244e19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('demographics', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('food_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recognition_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_food_images_user_captured_at', 'food_images', ['user_id', 'captured_at'], unique=False)
    op.create_table('nutrient_ledgers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('nutrient', sa.JSON(), nullable=False),
    sa.Column('percent_rda', sa.JSON(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nutrient_ledgers_user_week', 'nutrient_ledgers', ['user_id', 'week_start'], unique=False)
    op.create_table('food_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('food_image_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('fdc_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_image_id'], ['food_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_food_items_fdc_id', 'food_items', ['fdc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_food_items_fdc_id', table_name='food_items')
    op.drop_table('food_items')
    op.drop_index('idx_nutrient_ledgers_user_week', table_name='nutrient_ledgers')
    op.drop_table('nutrient_ledgers')
    op.drop_index('idx_food_images_user_captured_at', table_name='food_images')
    op.drop_table('food_images')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
